Enhancement/pagina registro
jorgeloria/proyecto-tienda-web pull request #7
Opened 2024-09-28 18:23 UTC by jorgeloria

2024-09-28 19:32 UTC, Monchez9 approved these changes

2024-09-28 21:12 UTC, andressero approved these changes

2024-09-28 22:01 UTC, BardockSSJL requested changes
Por favor arreglar problema en App.jsx. El archivo presenta el mensaje de conflicto de merge de git.

![image](https://github.com/user-attachments/assets/fb4992f2-e0ac-4425-a9c6-42bd6ff50eae)

2024-09-28 22:47 UTC, Monchez9 requested changes
hay un conflicto en App.jsx

2024-09-29 20:39 UTC, Monchez9 approved these changes
conflictos resueltos

2024-09-29 20:40 UTC, merged